# This file configures the workflows to trigger in our Prow jobs.
# See https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py.
python_paths:
  - kubeflow/katib/test/e2e/v1beta1
workflows:
  - name: e2e-v1beta1
    py_func: argo_workflow.create_workflow
    job_types:
      - presubmit
    include_dirs:
      - pkg/apis/controller/common/v1beta1/*
      - pkg/apis/controller/experiments/v1beta1/*
      - pkg/apis/controller/trials/v1beta1/*
      - pkg/apis/controller/suggestions/v1beta1/*
      - pkg/apis/controller/a*.go
      - pkg/apis/manager/health/*
      - pkg/apis/manager/v1beta1/*
      - pkg/apis/v1beta1/*
      - pkg/cert-generator/v1beta1/*
      - pkg/common/v1beta1/*
      - pkg/controller.v1beta1/*
      - pkg/db/v1beta1/*
      - pkg/earlystopping/v1beta1/*
      - pkg/metricscollector/v1beta1/*
      - pkg/new-ui/v1beta1/*
      - pkg/suggestion/v1beta1/*
      - pkg/ui/v1beta1/*
      - pkg/util/v1beta1/*
      - pkg/webhook/v1beta1/*
      - cmd/cert-generator/v1beta1/*
      - cmd/db-manager/v1beta1/*
      - cmd/earlystopping/medianstop/v1beta1/*
      - cmd/katib-controller/v1beta1/*
      - cmd/metricscollector/v1beta1/*
      - cmd/new-ui/v1beta1/*
      - cmd/suggestion/chocolate/v1beta1/*
      - cmd/suggestion/goptuna/v1beta1/*
      - cmd/suggestion/optuna/v1beta1/*
      - cmd/suggestion/hyperband/v1beta1/*
      - cmd/suggestion/hyperopt/v1beta1/*
      - cmd/suggestion/nas/darts/v1beta1/*
      - cmd/suggestion/nas/enas/v1beta1/*
      - cmd/suggestion/skopt/v1beta1/*
      - cmd/ui/v1beta1/*
      - examples/v1beta1/*
      - hack/*
      - sdk/python/v1beta1/*
      - test/e2e/v1beta1/*
      - manifests/v1beta1/*
      - scripts/v1beta1/*
      - prow_config.yaml
      - Makefile
    kwargs:
      registry: 809251082950.dkr.ecr.us-west-2.amazonaws.com
