---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: xgb-svhn-fpga
  namespace: kubeflow
spec:
  algorithm:
    algorithmName: random
  maxFailedTrialCount: 3
  maxTrialCount: 10
  objective:
    additionalMetricNames:
      - time
    goal: 0.99
    objectiveMetricName: accuracy
    type: maximize
  parallelTrialCount: 1
  parameters:
    - feasibleSpace:
        min: "0.00"
        max: "0.05"
      name: alpha
      parameterType: double
    - feasibleSpace:
        min: "0.1"
        max: "0.4"
      name: eta
      parameterType: double
    - feasibleSpace:
        min: "0.6"
        max: "1.0"
      name: subsample
      parameterType: double
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: alpha
        description: L1 regularization term on weights
        reference: alpha
      - name: eta
        description: Step size shrinkage used in update to prevent overfitting
        reference: eta
      - name: subsample
        description: Subsample ratio of the training instances
        reference: subsample
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          metadata:
            labels:
              inaccel/fpga: enabled
            annotations:
              inaccel/cli: |
                bitstream install --mode others https://store.inaccel.com/artifactory/bitstreams/xilinx/aws-vu9p-f1/shell-v04261818_201920.2/aws/com/inaccel/xgboost/0.1/2exact
          spec:
            containers:
              - name: training-container
                image: "docker.io/inaccel/jupyter:lab"
                command:
                  - python3
                  - XGBoost/parameter-tuning.py
                args:
                  - "--name=SVHN"
                  - "--test-size=0.35"
                  - "--tree-method=fpga_exact"
                  - "--max-depth=10"
                  - "--alpha=${trialParameters.alpha}"
                  - "--eta=${trialParameters.eta}"
                  - "--subsample=${trialParameters.subsample}"
                resources:
                  limits:
                    xilinx/aws-vu9p-f1: 1
            restartPolicy: Never
